stages:
  - ğŸ“¦ build
  - ğŸ¤ test
  - ğŸ¦„ quality
  - ğŸš€ deploy

ğŸ“œ pages:
  stage: ğŸš€ deploy
  script:
    - mkdir .public
    - mv docs/build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master